### ISSUE TITLE
"SyntaxError: Unexpected token ILLEGAL" when running 'volo grunt' on Windows

### ISSUE THREAD

**Issue by AndreTheHunter** [iceddev/frozen-dev-boilerplate#2]
I followed the steps at https://github.com/iceddev/frozen-dev-boilerplate#frozen-development-boilerplate and when running 'volo grunt' I get the following error:

```
...\node_modules\.bin\grunt:2
basedir=`dirname "$0"`
        ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:437:25)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
ERROR: Error
```

**Comment by monteslu** [comment]
thanks for the report

Could i get bit more info.

Which operating system, version of node, and version of volo?

**Comment by AndreTheHunter** [comment]
I ran the commands in the project dir in cmd.exe (I removed some unnecessary output):

```
C:\..>node -v
v0.8.20
C:\...>volo
volo v0.2.8, a JavaScript tool to make JavaScript projects. Allowed commands:

volofile commands:

grunt: Volo command for running grunt tasks using locally installed grunt
onCreate: Called upon creation of a new project - runs `npm install`

Standard volo commands:
...
C:\...>volo grunt -v

C:\...\node_modules\.bin\grunt:2
basedir=`dirname "$0"`
        ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:437:25)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
ERROR: Error
```

Windows 7 SP 1 (6.1 Build 7601 SP1)

I'm quite new to the world of nodejs so please let me know if I can provide any other information.

Thank you!

**Comment by yefremov** [comment]
First of all, make sure you have grunt installed globally:

``` bash
npm install -g grunt
```

Then make sure you have followed this instruction: [On Windows, why does my JS editor open when I try to run grunt?](http://gruntjs.com/frequently-asked-questions#on-windows-why-does-my-js-editor-open-when-i-try-to-run-grunt)

Just open cmd or Node.js command prompt and insert following and press return(enter):

``` bash
DOSKEY grunt=grunt.cmd $*
```

Finally if this is not helpful, your last chance is to access `node_modules/.bin` folder and double click on the file which represents command you want execute, `grunt.cmd` stands for `default`.

Anyway, thank you @AndreTheHunter, this is good catch, I didn't know that [volo-grunt](https://github.com/phated/volo-grunt) task existed, now we can try to fix this cross-platform issue in volo! :)

**Comment by AndreTheHunter** [comment]
Ok I managed to get it working.
I installed grunt globally and then entered "grunt.cmd" instead of "volo grunt".

I know that this not working wasn't your fault (I had no idea), so thanks heaps for the help!

**Comment by phated** [comment]
`volo grunt` is just a volo task I created to pass through commands from volo to grunt. You can use grunt standalone but I think it is nice to only need to install one tool globally (volo).  I will look into the `.cmd` thing, as I develop on Linux and not Windows.
