### ISSUE TITLE
FYI grunt-jasmine-runner does not work with grunt 0.4.0

### ISSUE THREAD

**Issue by AndreTheHunter** [iceddev/frozen-dev-boilerplate#3]
FYI

https://github.com/jasmine-contrib/grunt-jasmine-runner no longer works with grunt 0.4.0 and has been replaced by https://github.com/gruntjs/grunt-contrib-jasmine. 

There are also many other changes between 0.3 and and 0.4. See http://gruntjs.com/blog/2013-02-18-grunt-0.4.0-released and https://github.com/gruntjs/grunt/wiki/Upgrading-from-0.3-to-0.4

**Comment by phated** [comment]
Frozen will be updated to Grunt 0.4 in 0.3.0 and so will the boilerplate.  Currently it uses 0.3.17 and should continue to work until the next release of Frozen.
